[package]
name = "rust-sdk"
version = "0.1.0"
edition = "2021"
description = "cp-amm sdk"
authors = ["minh <minh@raccoons.dev>"]

[dependencies]
anyhow = "1.0.71"
cp-amm = { path = "../programs/cp-amm" }
ruint = "1.3.0"

[dev-dependencies]
bytemuck = { workspace = true}